/**
 * DO NOT EDIT THIS FILE DIRECTLY.
 * This file is generated following the conversion of 
 * @see [./node_modules/scratch-storage/src/index.js]{@link ./node_modules/scratch-storage/src/index.js}
 * 
 **/
import ScratchStorage  from "./ScratchStorage.mjs";

/**
 * Export for use with NPM & Node.js.
 * @type {ScratchStorage}
 */
export default ScratchStorage;
